sudo: false

dist: focal
language: node_js
node_js: node

cache:
  directories:
    - sysconfcpus
os:
  - linux

env: ELM_VERSION=0.19.1

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - node --version
  - npm --version
  - npm install elm@$ELM_VERSION elm-test@$ELM_VERSION elm-format@0.8.4
  # Faster compile on Travis.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 ./node_modules/.bin/elm-test --compiler $TRAVIS_BUILD_DIR/node_modules/.bin/elm
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 ./node_modules/.bin/elm-format --validate .
